name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_lines: yes
          plugin_languages_ignored: >-
            html, css, scss, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 4
          config_timezone: Asia/Manila
          token: ${{ secrets.METRICS_TOKEN }}
